

#pragma config(Sensor, S1,     button,         sensorNone)
#pragma config(Motor,  motorA,          a,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          LEFT,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          c,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          RIGHT,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int mode = 0;
	int speedd = 10;
  int speedb = 10;
	int SPIRAL = 0;
	int WALLFOLLOW = 1;

	while(true)
	{
		if(mode == SPIRAL)
		{
			motor(LEFT) = speedb;
      motor(RIGHT) = speedd;
      wait1Msec(1000);

   speedd = speedd + 10;
   speedb = speedb + 5;

   resetMotorEncoder(RIGHT);
   resetMotorEncoder(LEFT);
   if(SensorValue(button) == 1)
   {
     mode = WALLFOLLOW;
   }
	  }

		if(mode == WALLFOLLOW)
		{
	  if(SensorValue(button) == 0)
	{
		motor(LEFT) = 100;
		motor(RIGHT) = 75;
	}
	else
	{
		motor(LEFT) = -100;
		motor(RIGHT) = 100;
	}
	if(getMotorEncoder(LEFT) > 5000)
	{
		motor(LEFT) = 50;
		motor(RIGHT) = -50;
		wait1Msec(1000)
		motor(LEFT) = 100;
		motor(RIGHT) = 100;
	}


}



}
